//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoExterno.Transferencia
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestTransferenciaTED", Namespace="http://schemas.datacontract.org/2004/07/CloudDesignPatterns.Ambassador.Service.Se" +
        "rvicoTransferencia.Data")]
    public partial class RequestTransferenciaTED : object
    {
        
        private string AgenciaDestinoField;
        
        private string ContaDestinoField;
        
        private string DocumentoBeneficiarioField;
        
        private string InstituicaoDetinoField;
        
        private decimal ValorTransferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgenciaDestino
        {
            get
            {
                return this.AgenciaDestinoField;
            }
            set
            {
                this.AgenciaDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContaDestino
        {
            get
            {
                return this.ContaDestinoField;
            }
            set
            {
                this.ContaDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoBeneficiario
        {
            get
            {
                return this.DocumentoBeneficiarioField;
            }
            set
            {
                this.DocumentoBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstituicaoDetino
        {
            get
            {
                return this.InstituicaoDetinoField;
            }
            set
            {
                this.InstituicaoDetinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorTransferencia
        {
            get
            {
                return this.ValorTransferenciaField;
            }
            set
            {
                this.ValorTransferenciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoExterno.Transferencia.ITransferenciaTED")]
    public interface ITransferenciaTED
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferenciaTED/RealizaTransferenciaTED", ReplyAction="http://tempuri.org/ITransferenciaTED/RealizaTransferenciaTEDResponse")]
        System.Threading.Tasks.Task<string> RealizaTransferenciaTEDAsync(ServicoExterno.Transferencia.RequestTransferenciaTED requestTransferencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITransferenciaTEDChannel : ServicoExterno.Transferencia.ITransferenciaTED, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TransferenciaTEDClient : System.ServiceModel.ClientBase<ServicoExterno.Transferencia.ITransferenciaTED>, ServicoExterno.Transferencia.ITransferenciaTED
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransferenciaTEDClient() : 
                base(TransferenciaTEDClient.GetDefaultBinding(), TransferenciaTEDClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITransferenciaTED.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransferenciaTEDClient(EndpointConfiguration endpointConfiguration) : 
                base(TransferenciaTEDClient.GetBindingForEndpoint(endpointConfiguration), TransferenciaTEDClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransferenciaTEDClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransferenciaTEDClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransferenciaTEDClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransferenciaTEDClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransferenciaTEDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> RealizaTransferenciaTEDAsync(ServicoExterno.Transferencia.RequestTransferenciaTED requestTransferencia)
        {
            return base.Channel.RealizaTransferenciaTEDAsync(requestTransferencia);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransferenciaTED))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransferenciaTED))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9101/TransferenciaTEDService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransferenciaTEDClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITransferenciaTED);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransferenciaTEDClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITransferenciaTED);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITransferenciaTED,
        }
    }
}
